/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.giuseppelamalfa.gameofliferemastered.ui;

import com.giuseppelamalfa.gameofliferemastered.GridPanel;
import com.giuseppelamalfa.gameofliferemastered.gamelogic.simulation.SimulationInterface;
import com.giuseppelamalfa.gameofliferemastered.gamelogic.unit.UnitInterface;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;

/**
 *
 * @author glitchedcode
 */
public class GameStatusPanel extends javax.swing.JPanel implements MouseListener, MouseMotionListener, MouseWheelListener {

    GridPanel gridPanel;
    
    /**
     * Creates new form GameStatusPanel
     */
    public GameStatusPanel() {
        initComponents();
        Color col = new Color(0,0,0,0);
        setBackground(col);
        jPanel1.setBackground(col);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        turnCountLabel = new javax.swing.JLabel();
        gameModeLabel = new javax.swing.JLabel();
        filler = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        turnCountLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        turnCountLabel.setForeground(new java.awt.Color(255, 255, 255));
        turnCountLabel.setText("Turn: 99999");

        gameModeLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        gameModeLabel.setForeground(new java.awt.Color(255, 255, 255));
        gameModeLabel.setText("Sandbox");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gameModeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(turnCountLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turnCountLabel)
                    .addComponent(gameModeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setTurnCount(int val){
        turnCountLabel.setText("Turn: " + val);
    }
    
    public void update(SimulationInterface simulation){
        
    }
    
    public void setGridPanel(GridPanel panel)
    {
        addMouseListener(this);
        gridPanel = panel;
    }
    
   /*
    * MOUSE INPUT HANDLING
     */
    @Override
    public void mouseClicked(MouseEvent me)
    {
        gridPanel.mouseClicked(me);
    }

    @Override
    public void mouseMoved(MouseEvent me)
    {
        gridPanel.mouseMoved(me);
    }
    
    @Override
    public void mousePressed(MouseEvent me)
    {
        gridPanel.mousePressed(me);
    }

    @Override
    public void mouseDragged(MouseEvent me)
    {
        gridPanel.mouseDragged(me);
    }

    @Override
    public void mouseWheelMoved(MouseWheelEvent me)
    {
        gridPanel.mouseWheelMoved(me);
    }
    // don't need these
    @Override
    public void mouseReleased(MouseEvent me) {
    }
    @Override
    public void mouseEntered(MouseEvent me){}
    @Override
    public void mouseExited(MouseEvent me)    {    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler;
    private javax.swing.JLabel gameModeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel turnCountLabel;
    // End of variables declaration//GEN-END:variables
}
