/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.giuseppelamalfa.gameofliferemastered.utils;

import com.giuseppelamalfa.gameofliferemastered.gamelogic.SimulationInterface;
import java.awt.Color;

/**
 *
 * @author glitchedcode
 */
public class GameStatusPanel extends javax.swing.JPanel {

    /**
     * Creates new form GameStatusPanel
     */
    public GameStatusPanel() {
        initComponents();
        Color col = new Color(0,0,0,0);
        setBackground(col);
        jPanel1.setBackground(col);
        gameStatus.setBackground(col);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        turnCountLabel = new javax.swing.JLabel();
        gameModeLabel = new javax.swing.JLabel();
        gameStatus = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        turnCountLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        turnCountLabel.setText("Turn: 99999");

        gameModeLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        gameModeLabel.setText("Sandbox");

        gameStatus.setEditable(false);
        gameStatus.setColumns(20);
        gameStatus.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        gameStatus.setLineWrap(true);
        gameStatus.setRows(5);
        gameStatus.setText("wsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss");
        gameStatus.setWrapStyleWord(true);
        gameStatus.setBorder(null);
        gameStatus.setFocusable(false);
        gameStatus.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gameModeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(turnCountLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turnCountLabel)
                    .addComponent(gameModeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setTurnCount(int val){
        turnCountLabel.setText("Turn: " + val);
    }
    
    public void update(SimulationInterface simulation){
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameModeLabel;
    private javax.swing.JTextArea gameStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel turnCountLabel;
    // End of variables declaration//GEN-END:variables
}
